# Generated by Django 5.1.5 on 2025-01-30 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botresponse',
            old_name='bot_response',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='botresponse',
            old_name='user_message',
            new_name='response',
        ),
        migrations.RemoveField(
            model_name='botresponse',
            name='chat_id',
        ),
    ]
